/**
 * Obsidian Vault Integration
 * 
 * Stores routing decisions and context as markdown files
 * compatible with Obsidian note-taking app.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface VaultConfig {
  path: string;
  autoSave: boolean;
  maxFileAge: number; // days
}

export interface RoutingDecision {
  id: string;
  timestamp: number;
  prompt: string;
  context: any;
  selectedProvider: string;
  selectedModel: string;
  reasoning: string;
  cost: number;
  latency: number;
}

export class ObsidianVault {
  private config: VaultConfig;
  private decisions: RoutingDecision[];

  constructor(config: Partial<VaultConfig> = {}) {
    this.config = {
      path: config.path || './vault',
      autoSave: config.autoSave !== false,
      maxFileAge: config.maxFileAge || 30
    };
    this.decisions = [];
    this.ensureDirectory();
  }

  private ensureDirectory() {
    if (!fs.existsSync(this.config.path)) {
      fs.mkdirSync(this.config.path, { recursive: true });
    }
  }

  /**
   * Save a routing decision
   */
  async saveDecision(decision: RoutingDecision): Promise<string> {
    this.decisions.push(decision);
    
    const filename = `routing-decision-${decision.id}.md`;
    const filepath = path.join(this.config.path, filename);
    const content = this.formatDecisionAsMarkdown(decision);
    
    fs.writeFileSync(filepath, content, 'utf-8');
    
    // Update index
    await this.updateIndex();
    
    return filepath;
  }

  /**
   * Format decision as markdown
   */
  private formatDecisionAsMarkdown(decision: RoutingDecision): string {
    const date = new Date(decision.timestamp).toISOString();
    
    return `# Routing Decision ${decision.id}

**Date:** ${date}
**Prompt:** ${this.escapeMarkdown(decision.prompt.substring(0, 200))}

## Decision

| Field | Value |
|-------|-------|
| Provider | ${decision.selectedProvider} |
| Model | ${decision.selectedModel} |
| Reasoning | ${this.escapeMarkdown(decision.reasoning)} |
| Cost | $${decision.cost.toFixed(4)} |
| Latency | ${decision.latency}ms |

## Context

\`\`\`json
${JSON.stringify(decision.context, null, 2)}
\`\`\`

## Prompt (Full)

${decision.prompt}

---
*Generated by A3M Router*
`;
  }

  /**
   * Escape markdown special characters
   */
  private escapeMarkdown(text: string): string {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/\*/g, '\\*')
      .replace(/#/g, '\\#')
      .replace(/\|/g, '\\|')
      .replace(/`/g, '\\`')
      .replace(/\[/g, '\\[')
      .replace(/\]/g, '\\]')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/>/g, '\\>')
      .replace(/_/g, '\\_');
  }

  /**
   * Update the vault index
   */
  private async updateIndex() {
    const indexPath = path.join(this.config.path, 'routing-index.md');
    
    const lines = [
      '# Routing Decisions Index',
      '',
      `Last updated: ${new Date().toISOString()}`,
      '',
      `Total decisions: ${this.decisions.length}`,
      '',
      '## Recent Decisions',
      ''
    ];

    for (const decision of this.decisions.slice(-20).reverse()) {
      const date = new Date(decision.timestamp).toLocaleDateString();
      lines.push(`- [${decision.id}](./routing-decision-${decision.id}.md) - ${date} - ${decision.selectedProvider}/${decision.selectedModel}`);
    }

    fs.writeFileSync(indexPath, lines.join('\n'), 'utf-8');
  }

  /**
   * Get recent decisions
   */
  getRecentDecisions(count = 10): RoutingDecision[] {
    return this.decisions.slice(-count).reverse();
  }

  /**
   * Search decisions
   */
  searchDecisions(query: string): RoutingDecision[] {
    const queryLower = query.toLowerCase();
    return this.decisions.filter(d => 
      d.prompt.toLowerCase().includes(queryLower) ||
      d.selectedProvider.toLowerCase().includes(queryLower) ||
      d.selectedModel.toLowerCase().includes(queryLower)
    );
  }

  /**
   * Export all decisions
   */
  async exportAll(filepath: string) {
    const content = this.decisions.map(d => 
      this.formatDecisionAsMarkdown(d)
    ).join('\n\n---\n\n');

    fs.writeFileSync(filepath, content, 'utf-8');
  }

  /**
   * Get vault statistics
   */
  getStats() {
    return {
      totalDecisions: this.decisions.length,
      vaultPath: this.config.path,
      fileCount: fs.readdirSync(this.config.path).filter(f => f.endsWith('.md')).length,
      totalSize: this.getDirectorySize(this.config.path)
    };
  }

  private getDirectorySize(dir: string): number {
    let size = 0;
    const files = fs.readdirSync(dir);
    
    for (const file of files) {
      const filepath = path.join(dir, file);
      const stat = fs.statSync(filepath);
      
      if (stat.isDirectory()) {
        size += this.getDirectorySize(filepath);
      } else {
        size += stat.size;
      }
    }
    
    return size;
  }

  /**
   * Clean old files
   */
  async cleanOldFiles() {
    const maxAge = this.config.maxFileAge * 24 * 60 * 60 * 1000;
    const now = Date.now();
    const files = fs.readdirSync(this.config.path);
    let cleaned = 0;

    for (const file of files) {
      if (!file.endsWith('.md') || file === 'routing-index.md') continue;
      
      const filepath = path.join(this.config.path, file);
      const stat = fs.statSync(filepath);
      
      if (now - stat.mtimeMs > maxAge) {
        fs.unlinkSync(filepath);
        cleaned++;
      }
    }

    return cleaned;
  }
}

export default ObsidianVault;
